sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 13306
    database: sky_take_out
    username: root
    password: root
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: 11
    access-key-secret: 111
    bucket-name: wzlwaimai
  redis:
    host: localhost
    port: 6379
    database: 2
  wechat:
    appid: 222
    secret: 333

