sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 13306
    database: sky_take_out
    username: root
    password: root
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tAFqRCr251gRTpXcuVp
    access-key-secret: uJbDosT4WP8IjrHfdD4v5bMjsJ7Zgf
    bucket-name: wzlwaimai
  redis:
    host: localhost
    port: 6379
    database: 2
  wechat:
    appid: wx7ab387f6274666f7
    secret: 54b2c6ab6ef592fed157ef0db63517c7

